# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ pipeline-test ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # vm:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo This job does not specify a container.
  #         echo It runs directly on the virtual machine.
  #       name: Run on VM
  container:
    runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
          cd ${home}
          sh ls
        name: Run in container
          # chmod +x /__w/time-jobs/time-jobs/scripts/run.sh
          # ./scripts/run.sh
          # echo "este es el pwd"
          # pwd